name: build-workflow
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: install-helm
        run: |
          wget https://get.helm.sh/helm-v3.5.0-linux-amd64.tar.gz -O /tmp/helm-v3.5.0-linux-amd64.tar.gz
          mkdir /tmp/bin -p; tar xzf /tmp/helm-v3.5.0-linux-amd64.tar.gz -C /tmp/bin --strip-components=1;
          PATH=/tmp/bin:$PATH
      - name: build-base-image
        run: |
          cd base-image && make
      - name: lint-test-config-reloader
        run: |
          cd config-reloader && make test
      - name: build-config-reloader
        run: |
          cd config-reloader && make build-image TAG=v$GITHUB_SHA_SHORT
      - name: load-image
        run: |
          kind load docker-image vmware/kube-fluentd-operator:v$GITHUB_SHA_SHORT
      - name: install-log-router
        run: |
          cd charts
          PATH=$PATH:/tmp/bin helm upgrade --install --set image.tag=v$GITHUB_SHA_SHORT --set rbac.create=true --wait --timeout 60s  log-router ./log-router
      - name: build-chart
        working-directory: charts/log-router
        run: make
      - name: create-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: charts/log-router/log-router-0.4.0.tgz
