name: release-workflow
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
    - '*'

jobs:
  publish:
    name: publish-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build-base
        run: |
          cd base-image && make build-image
      - name: push-image
        run: |
          cd config-reloader && make push-image
        env:
          TAG: ${{github.ref_name}}

  release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-helm
        run: |
          wget https://get.helm.sh/helm-v3.5.0-linux-amd64.tar.gz -O /tmp/helm-v3.5.0-linux-amd64.tar.gz
          mkdir /tmp/bin -p; tar xzf /tmp/helm-v3.5.0-linux-amd64.tar.gz -C /tmp/bin --strip-components=1;
          PATH=/tmp/bin:$PATH
      - name: build-chart
        working-directory: charts/log-router
        run: make
      - name: create-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: charts/log-router/log-router-0.4.0.tgz
